ALTER TABLE T_STAFF
 ADD ADDR VARCHAR (510)
ALTER TABLE T_STAFF
  ADD BIRTHDAY DATETIME
ALTER TABLE T_STAFF
 ADD BRANCHCODE VARCHAR (12)
ALTER TABLE T_STAFF
 ADD CERTNO VARCHAR (36)
ALTER TABLE T_STAFF
  ADD DIMIDATE DATETIME
ALTER TABLE T_STAFF
 ADD DUTYCODE VARCHAR (4)
ALTER TABLE T_STAFF
 ADD FUNDEF VARCHAR (510)
ALTER TABLE T_STAFF
 ADD ISLOCKED INT
ALTER TABLE T_STAFF
 ADD ISSUPER INT
ALTER TABLE T_STAFF
 ADD LASTTIME INT
ALTER TABLE T_STAFF
 ADD MNGFUNDEF VARCHAR (510)
ALTER TABLE T_STAFF
 ADD NAME VARCHAR (60)
ALTER TABLE T_STAFF
 ADD NODENO VARCHAR (12)
ALTER TABLE T_STAFF
 ADD PASSWORD VARCHAR (40)
ALTER TABLE T_STAFF
 ADD PHONE VARCHAR (60)
ALTER TABLE T_STAFF
  ADD PWLASTUPDDATE DATETIME
ALTER TABLE T_STAFF
 ADD SEQID VARCHAR (100)
ALTER TABLE T_STAFF
 ADD SEX VARCHAR (2)
ALTER TABLE T_STAFF
 ADD STAFFNO VARCHAR (12)
ALTER TABLE T_STAFF
 ADD STATUS VARCHAR (4)
ALTER TABLE T_STAFF
 ADD SUPERSTAFFNO VARCHAR (12)
ALTER TABLE T_STAFF
 ADD WRONGPWDTIMES INT
